### ISSUE TITLE
Add key visual + logo

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#10]
Here are the mockups (by @RalloTubbs):
## desktop

![](https://trello-attachments.s3.amazonaws.com/5197b0ce10998eb47e00d095/57cfd143c10bba910860dcbb/db65bb6300688953ec1932525a19cd73/startpage_1_0.png)
## tablet

![](https://trello-attachments.s3.amazonaws.com/5197b0ce10998eb47e00d095/57cfd143c10bba910860dcbb/61fed37c47015d5c07393a540969b1b1/startpage_1_0_860.png)
## mobile

![](https://trello-attachments.s3.amazonaws.com/5197b0ce10998eb47e00d095/57cfd143c10bba910860dcbb/f744b112c79a060c92314474152eca1d/startpage_1_0_320.jpg)

**Comment by Kriesse** [comment]
@RalloTubbs Just noticed the main info is missing:

CSSconf EU
Friday, May 5 2017
Berlin, Germany

**Comment by RalloTubbs** [comment]
tomorrow :)

**Comment by Kriesse** [comment]
@RalloTubbs Cool, no rush :)
Work in progress here: http://2017.cssconf.eu/

I added two lines of text which we'll need to catch frequently asked questions (we're already getting questions like "when does this and that open?") and moved the button to the top bar for now.

**Comment by Kriesse** [comment]
Done, closing. Let's file separate issues for improvements.
