### ISSUE TITLE
some graphics for tweets/sharing

### ISSUE THREAD

**Issue by RalloTubbs** [cssconf/2017.cssconf.eu#15]
![tweet1](https://cloud.githubusercontent.com/assets/7797904/19221618/5ac20fde-8e47-11e6-935c-dc1edce0053d.png)
![tweet2](https://cloud.githubusercontent.com/assets/7797904/19221617/5ac18e56-8e47-11e6-87de-3f10aeb49359.png)
![tweet3](https://cloud.githubusercontent.com/assets/7797904/19221616/5ac113e0-8e47-11e6-8e80-3010dd4371c0.png)
![tweet4](https://cloud.githubusercontent.com/assets/7797904/19221619/5ac3eb1a-8e47-11e6-8d64-5f38fd57f195.png)

**Comment by Kriesse** [comment]
I'll close this issue as it's done – @RalloTubbs Can you create a folder in the dropbox for those and upcoming social media assets, so we have them available?
