### ISSUE TITLE
Improve hover state on "CSSconf EU 2017" in top bar

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#16]
It's kind of ugly right now and creates the impression that only "2017" is hovered.

@RalloTubbs Any ideas how to improve?

![image](https://cloud.githubusercontent.com/assets/53684/19221809/f87ce566-8e4a-11e6-8c41-3383e8d28d60.png)

**Comment by RalloTubbs** [comment]
just thought about this, too...
if we don't have a link here so far it could be a small hidden easter egg???

maybe on hover (mousehand shows up) you can click, then it starts an animation, like the "2017" is changing the colours very fast: red, yellow, blue, green, ... then it stops, on click the animation starts again

or sth else :)

**Comment by sfrdmn** [comment]
The original here issue seems to have been resolved. If we want to do even more with the hover state, maybe we can bring it up in another discussion, but seems like we can close this issue
