### ISSUE TITLE
Review Content of all Pages

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#18]
- [ ] Code of Conduct
- [ ] Accessibility
- [ ] Diversity Tickets
- [ ] Scholarships
- [ ] CfS (https://github.com/cssconf/2017.cssconf.eu/issues/28)
- [ ] Team
- [ ] Info
- [ ] Speakers
- [ ] Schedule

**Comment by Kriesse** [comment]
@retrospekt @Lucie-H Can you tackle this? We need this done by November 15, when the Call for Speakers opens.

**Comment by Lucie-H** [comment]
I can have a look at the weekend, won't have time before that unfortunately.

**Comment by Kriesse** [comment]
Closing, apparently not actionable. Will file separate issue for each page when needed.
