### ISSUE TITLE
Update CSS on Blog

### ISSUE THREAD

**Issue by RalloTubbs** [cssconf/2017.cssconf.eu#20]
first quick update 0.1
![blog-level1](https://cloud.githubusercontent.com/assets/7797904/19451158/7d574a94-94ac-11e6-8582-c6398fafec5a.jpg)

**Comment by Kriesse** [comment]
Closing, as this is done in a separate repo:
https://github.com/cssconf/blog-server/

@RalloTubbs Please file all blog-related issues in this repo from now on :)
