### ISSUE TITLE
Call for Speakers Page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#28]
Our Call for Speakers launches on November 17 (it remains open for 6+ weeks).
We need a page that has all the information, and a submission form.

- [x] review copy
- [x] create google form
- [x] embed and style google form

2015 version:
http://2015.cssconf.eu/call-for-speakers/

Current status of 2017:
http://2017.cssconf.eu/call-for-speakers/

**Comment by retrospekt** [comment]
The first three items are complete, I'm working on the fourth one; 

I think the last point can wait for now :)

**Comment by retrospekt** [comment]
Ah and the form:

https://docs.google.com/a/cssconf.eu/forms/d/e/1FAIpQLScc1spXJyoYCeCzkKa-H2y57oCdRGxNuwHVGIPKItD_cZXK2Q/viewform

**Comment by Kriesse** [comment]
@retrospekt Awesome! I'll file separate issues for the remaining tasks.
