### ISSUE TITLE
Scholarships Page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#29]
We need a page where people can apply for scholarships. It goes live on November 20.

- [x] copy that explains how scholarships work, what they include etc
- [x] embed googleform, style it
- [ ] coordinate with jsconf – maybe we want the same form?

**Comment by Kriesse** [comment]
still proof-reading, some comments:
- add link to scholarships
- add that we disable comments on video recordings by default

**Comment by Kriesse** [comment]
@verpixelt Can you add the link to the form (when you have it?)

**Comment by verpixelt** [comment]
Progress visible in #47

**Comment by verpixelt** [comment]
I've share the document with JSconf and notified them via Slack.

**Comment by Kriesse** [comment]
@verpixelt Awesome! I filed a PR on the JSConf page. Let's merge this one in as soon as they go live with theirs :)
