### ISSUE TITLE
Add CTA button to Call for Speakers

### ISSUE THREAD

**Issue by retrospekt** [cssconf/2017.cssconf.eu#31]
Add two buttons to the call for speakers page; one at the top, where the Newsletter button is right now, and one right at the bottom. Button should say:

Submit a proposal 🚀

**Comment by lukaszklis** [comment]
@retrospekt just to be 100% correct on this one, this is supposed to be changed _ONLY_ on the "Call for Speakers" page, isn't it?

**Comment by retrospekt** [comment]
Yes, for now! We may add it to other pages later when it's closer to the deadline! :)

**Comment by Kriesse** [comment]
@lukaszklis On November 17 this button should go live everywhere!
