### ISSUE TITLE
Call for Speakers Googleform: Send feedback?

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#34]
Investigate: can we tweak the google form so that people receive a confirmation that they submitted?

Right now the googleform acts like a black hole. People submit their talk and never see it again, until we notify them 2 months later.

A simple feedback email ("Thanks for your submission, contact us at contact@cssconf.eu for questions") would be great.

https://docs.google.com/a/cssconf.eu/forms/d/e/1FAIpQLScc1spXJyoYCeCzkKa-H2y57oCdRGxNuwHVGIPKItD_cZXK2Q/viewform

**Comment by retrospekt** [comment]
Hi. I created that, it has been activated. There is also the option to send a copy of the form with the submitter's responses for their reference, though this is currently disabled!

**Comment by lukaszklis** [comment]
You can "trick" it with some embedded scripts inside of the Google Form (sent a link to an article about it on Slack). Will give it a try later and let you know.

**Comment by Kriesse** [comment]
@lukaszklis @retrospekt Can we close this?
