### ISSUE TITLE
Call for Speakers: Embed Googleform

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#35]
On this page:
http://2017.cssconf.eu/call-for-speakers/

embed the googleform:
https://docs.google.com/a/cssconf.eu/forms/d/e/1FAIpQLScc1spXJyoYCeCzkKa-H2y57oCdRGxNuwHVGIPKItD_cZXK2Q/viewform

**Comment by lukaszklis** [comment]
Should we add a new section there too called "Submit a proposal"?

**Comment by verpixelt** [comment]
Sounds good to me! Will you take care of it? :)

**Comment by lukaszklis** [comment]
Yup

**Comment by lukaszklis** [comment]
This has to be merged _after_ #37. Adding a new property to the `_config.yml` will do the trick with showing the CTAs on the CfS page.
