### ISSUE TITLE
Thank-You-Section for individuals who bought diversity support ticktets.

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#51]
We need a little section on the website where we thank individuals who bought diversity tickets. A list of names, a simple paragraph. Should probably be a partial that we can re-use on these pages:
/diversity-support-tickets
/scholarships
/sponsors

Text:
We are very grateful and are saying a big Thank You to those companies and individuals who donated to our scholarship program. [list of names]

It could have a nice :heart: icon or something, and definitely a CTA “Buy a diversity ticket"

**Comment by lukaszklis** [comment]
@Kriesse do we have a list of names and they approval to publish those?

**Comment by Kriesse** [comment]
@lukaszklis The list consists of:
- people who bought a diversity support ticket via ti.to. We ask them whether they want to be listed, and under which name.
- companies who sponsor a diversity support ticket (so far that's Github)

Both lists will hopefully keep growing, I'll provide you with updates (also feel free to remind me)!
