### ISSUE TITLE
Speaker images’ shadow is cut off

### ISSUE THREAD

**Issue by lukaszklis** [cssconf/2017.cssconf.eu#59]
See the attachment. On the right side of the image, the shadow looks like it’s cut off.

![shadow-cut-off](https://cloud.githubusercontent.com/assets/7797904/23201603/96e3d030-f8da-11e6-8405-d5efe0f9fc72.png)

**Comment by lukaszklis** [comment]
@RalloTubbs could you confirm that it’s still happening?

**Comment by RalloTubbs** [comment]
looks like it's fixed

**Comment by lukaszklis** [comment]
Let’s close it for now, and in case it happens again, we’ll re-open this issue.
