### ISSUE TITLE
ready for dev: all graphics/assets for David and Guil

### ISSUE THREAD

**Issue by RalloTubbs** [cssconf/2017.cssconf.eu#68]
portraits and shapes svgs:
speaker photos: https://www.dropbox.com/sh/zjf7kfr5xjwhgnx/AACKdGdvhBhk_p1OJzrD5cBia?dl=0

shapes David: 3&4
shapes Guil: 11&12
https://www.dropbox.com/sh/hjtlvlf1ne8dgqm/AACA_eKqaNySL-XEUFB5dSzWa?dl=0

--

how the headers look like:
https://www.dropbox.com/sh/uefd0mzahnttnhl/AABz4qUbHhN0e71QbfMZQR9oa?dl=0

--

**Comment by Kriesse** [comment]
@sfrdmn can you link to a preview / screenshot when this is done?
