### ISSUE TITLE
Post-conference website

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#92]
Immediately after the conf, it should say a big "Thank you", show the group photo, link to the video recordings.

It should also point to twitter and newsletter, so people can follow the updates about 2018 (or whenever the next conf will be)

@RalloTubbs can you help with design?

**Comment by lukaszklis** [comment]
The page from 2015: http://2015.cssconf.eu/

**Comment by Kriesse** [comment]
Just in case, we probably should already create 2018.cssconf.eu with a "coming soon" teaser

**Comment by lukaszklis** [comment]
AFAIR @usefulthink or @frontdevde have access to manage DNS entries for cssconf.eu.
