### ISSUE TITLE
Make super compact, mobile-optimized version of the schedule

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#96]
The current schedule does not offer good UX for the conference day situation.
Attendees, speakers, and we will check the schedule all the time, and we should make that easy.
The long scrolling does not help to get an overview. It looks nice on desktop, but will be very annoying on the conference day.
Let's fix this!

We need a very compact layout that shows as many talks as possible on one (phone) screen
- [ ] remove header
- [x] remove speaker photos 
- [x] remove "learn more about…" links

Here's a mockup done in the browser, shouldn't take long to implement.
Let's focus on getting it done, we can iterate on design later.
![image](https://cloud.githubusercontent.com/assets/53684/25385213/97008cce-29c3-11e7-8695-bdfbe8cb51a4.png)

Nice to have, but lower priority: Make this page as fast as possible. 
Right now I get this when throttling to good 2G:
![image](https://cloud.githubusercontent.com/assets/53684/24837558/11e4ac16-1d37-11e7-8e17-2fdaa3fdae8a.png)
We have to assume that wifi won't work perfectly in the venue, so let's improve this.

**Comment by Kriesse** [comment]
ping @RalloTubbs – can we add Tilman to this? What's his github name?

**Comment by Kriesse** [comment]
"Drinks" and "Dinner" should be one section. Let's just call it "Dinner" maybe.

**Comment by Kriesse** [comment]
@lukaszklis @sfrdmn Can one of you take this on? Should mostly be a quick adjusting of flexbox properties for a mobile media-query.

**Comment by lukaszklis** [comment]
@Kriesse might have some time tomorrow, I’d also suggest removing the vertical line.

**Comment by Kriesse** [comment]
@lukaszklis good point! or even better, the line good still go through the center of the block with the time, i.e. move it to the left a bit.
